const STARTING_GOLD = 50

const GOLD_MINE_COST = -1
const LAB_COST = 50
const LAB_RATE = 0.95
const BUILDING_COST_INCREASE_RATE = 1.1

const BASE_MAX_HP = 3000
const FRIENDLY_BASE_X = 200
const ENEMY_BASE_X = 1030
const ENEMY_BASE_HP_BAR_X_OFFSET = -135
