const STARTING_GOLD = 50

const GOLD_MINE_COST = 75
const GOLD_MINE_COST_INCREASE_RATE = 1.2
const LAB_COST = 50
const LAB_DISCOUNT_RATE = 0.95
const LAB_COST_INCREASE_RATE = 1.2

const BASE_MAX_HP = 3000
const FRIENDLY_BASE_X = 150
const ENEMY_BASE_X = 1080
const ENEMY_BASE_HP_BAR_X_OFFSET = -135

const GRAVITY_Y = 100
