extends Node

const STARTING_GOLD = 50

const GOLD_MINE_COST = 65
const GOLD_MINE_COST_INCREASE_RATE = 1.15
const LAB_COST = 65
const LAB_DISCOUNT_RATE = 0.95
const LAB_COST_INCREASE_RATE = 1.15

const BASE_MAX_HP = 1000
const FRIENDLY_BASE_X = 125
const ENEMY_BASE_X = 1025
const ENEMY_BASE_HP_BAR_X_OFFSET = -135

const GRAVITY_Y = 100
