const SLIME = {
	"NAME": "SLIME",
	"COST": 50,
	"GOLD_DROP": 16,
	"MOVE_SPEED": 60,
	"MAX_HP": 24,
	"ATTACK_DMG": 20,
	"ATTACK_SPD": 2.5,
	"ATTACK_RANGE": 150,
	"SPAWN_WAIT": 0.8,
	"SPEED_SCALE": 0.75,
}

const GOBLIN = {
	"NAME": "GOBLIN",
	"COST": 30,
	"GOLD_DROP": 10,
	"MOVE_SPEED": 100,
	"MAX_HP": 65,
	"ATTACK_DMG": 6,
	"ATTACK_SPD": 0.5,
	"ATTACK_RANGE": 30,
	"SPAWN_WAIT": 0.8,
	"SPEED_SCALE": 2.0,
}

const GIANT = {
	"NAME": "GIANT",
	"COST": 130,
	"GOLD_DROP": 43,
	"MOVE_SPEED": 25,
	"MAX_HP": 450,
	"ATTACK_DMG": 60,
	"ATTACK_SPD": 3.0,
	"ATTACK_RANGE": 75,
	"SPAWN_WAIT": 2.0,
	"SPEED_SCALE": 0.5,
}
