extends "./base_troop.gd"

func _ready() -> void:
	NAME = MONSTER_T.GIANT.NAME
	MOVE_SPEED = MONSTER_T.GIANT.MOVE_SPEED
	ATTACK_RANGE = MONSTER_T.GIANT.ATTACK_RANGE
	ATTACK_DMG = MONSTER_T.GIANT.ATTACK_DMG
	ATTACK_SPD = MONSTER_T.GIANT.ATTACK_SPD
	MAX_HP = MONSTER_T.GIANT.MAX_HP
	GOLD_DROP = MONSTER_T.GIANT.GOLD_DROP
	SPAWN_WAIT = MONSTER_T.GIANT.SPAWN_WAIT
	SPEED_SCALE = MONSTER_T.GIANT.SPEED_SCALE
	super()
