extends "./base_troop.gd"

func _ready() -> void:
	MOVE_SPEED = MONSTER_T.GOBLIN.MOVE_SPEED
	ATTACK_RANGE = MONSTER_T.GOBLIN.ATTACK_RANGE
	ATTACK_DMG = MONSTER_T.GOBLIN.ATTACK_DMG
	ATTACK_SPD = MONSTER_T.GOBLIN.ATTACK_SPD
	MAX_HP = MONSTER_T.GOBLIN.MAX_HP
	GOLD_DROP = MONSTER_T.GOBLIN.GOLD_DROP
	SPAWN_WAIT = MONSTER_T.GOBLIN.SPAWN_WAIT
	SPEED_SCALE = MONSTER_T.GOBLIN.SPEED_SCALE
	super()
