extends "./base_troop.gd"

func _ready() -> void:
	NAME = MONSTER_T.SLIME.NAME
	MOVE_SPEED = MONSTER_T.SLIME.MOVE_SPEED
	ATTACK_RANGE = MONSTER_T.SLIME.ATTACK_RANGE
	ATTACK_DMG = MONSTER_T.SLIME.ATTACK_DMG
	ATTACK_SPD = MONSTER_T.SLIME.ATTACK_SPD
	MAX_HP = MONSTER_T.SLIME.MAX_HP
	GOLD_DROP = MONSTER_T.SLIME.GOLD_DROP
	SPAWN_WAIT = MONSTER_T.SLIME.SPAWN_WAIT
	SPEED_SCALE = MONSTER_T.SLIME.SPEED_SCALE
	super()
